import { useEffect, useState } from 'react'
import { Link } from 'react-router'
import { baseurl } from '../API/BaseUrl'

const categories = ['Roads & sidewalks', 'Waste & sanitation', 'Street lighting', 'Water & drainage', 'Parks & public spaces', 'Other']
const statusClass = (status = '') => /complete|resolved/i.test(status) ? 'resolved' : /progress/i.test(status) ? 'progress' : 'pending'
const getRows = (data) => Array.isArray(data) ? data : data?.complaints || data?.data || data?.items || []

function ReportCard({ item }) {
  return <article className="issue-card">
    {item.image && <img className="issue-image" src={item.image.startsWith('http') || item.image.startsWith('data:') ? item.image : `${baseurl}/uploads/${item.image}`} alt="" onError={e => { e.currentTarget.style.display = 'none' }} />}
    <div className="issue-content"><div className="issue-meta"><span>{item.category || 'Community'}</span><span className={`issue-status ${statusClass(item.status)}`}>{item.status || 'Pending'}</span></div>
    <h3>{item.title || 'Untitled report'}</h3><p>{item.description || 'No description provided.'}</p><div className="issue-bottom"><span>⌖ {item.location || 'Location not specified'}</span><span>{item.create_at ? new Date(item.create_at).toLocaleDateString() : ''}</span></div></div>
  </article>
}

export function Explore() {
  const [items, setItems] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [query, setQuery] = useState(''), [category, setCategory] = useState('All issues')
  useEffect(() => { fetch(`${baseurl}/Showallcomplain`).then(r => { if (!r.ok) throw new Error('Could not load community reports'); return r.json() }).then(data => setItems(getRows(data))).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [])
  const visible = items.filter(i => (!query || `${i.title} ${i.description} ${i.location}`.toLowerCase().includes(query.toLowerCase())) && (category === 'All issues' || i.category?.toLowerCase() === category.toLowerCase()))
  return <main className="page-wrap"><div className="page-heading"><div><span className="eyebrow">COMMUNITY BOARD</span><h1>See what needs attention.</h1><p>Browse local reports and follow their progress.</p></div><Link className="button button-primary" to="/report">＋ Report an issue</Link></div><div className="filters"><label className="search-box">⌕ <input placeholder="Search reports or locations" value={query} onChange={e => setQuery(e.target.value)} /></label><select value={category} onChange={e => setCategory(e.target.value)}><option>All issues</option>{categories.map(c => <option key={c}>{c}</option>)}</select></div>{loading ? <div className="empty-state">Loading community reports…</div> : error ? <div className="notice error">{error}. Check that the FastAPI server is running.</div> : visible.length ? <div className="issue-grid">{visible.map((item, i) => <ReportCard key={item.complain_id || i} item={item} />)}</div> : <div className="empty-state"><span>◎</span><h3>No reports found</h3><p>Try another search or submit the first report in your area.</p><Link className="button button-primary" to="/report">Report an issue</Link></div>}</main>
}

export function Report() {
  const [form, setForm] = useState({ title: '', category: categories[0], location: '', description: '', image: '' }), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  const submit = async e => { e.preventDefault(); setBusy(true); setMessage(''); try { const token = localStorage.getItem('lm_token'); if (!token) throw new Error('Please log in before submitting a report.'); const r = await fetch(`${baseurl}/complain_create`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(form) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.detail || 'Could not submit your report.'); setMessage('Your report has been submitted. Thank you for helping your community.'); setForm({ title: '', category: categories[0], location: '', description: '', image: '' }) } catch (e) { setMessage(e.message) } finally { setBusy(false) } }
  return <main className="form-page"><div className="form-intro"><span className="eyebrow">MAKE A DIFFERENCE</span><h1>Tell us what needs fixing.</h1><p>Share a clear description and location so the right city team can take a look.</p><div className="form-tip"><span>✳</span><div><b>Small details help</b><p>Add a nearby landmark and a photo link if you have one.</p></div></div></div><form className="panel report-form" onSubmit={submit}><h2>Issue details</h2><p className="muted">Fields marked with * are required.</p>{message && <div className={`notice ${message.startsWith('Your report') ? 'success' : 'error'}`}>{message}</div>}<label>Issue title *<input required maxLength="120" placeholder="e.g. Streetlight out on Oak Avenue" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Category *<select required value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label>Location *<input required placeholder="Street, neighborhood, or nearby landmark" value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} /></label><label>Description *<textarea required rows="5" maxLength="1200" placeholder="What happened? When did you notice it?" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><label>Photo URL <input type="url" placeholder="https://…" value={form.image} onChange={e => setForm({ ...form, image: e.target.value })} /><small>Paste a link to an image. The current API accepts an image URL, not file uploads.</small></label><button className="button button-primary full" disabled={busy}>{busy ? 'Submitting…' : 'Submit report →'}</button></form></main>
}

export function Dashboard({ admin = false }) {
  const [items, setItems] = useState([]), [query, setQuery] = useState(''), [category, setCategory] = useState('All categories'), [state, setState] = useState({ loading: true, error: '' }), [notice, setNotice] = useState('')
  const token = localStorage.getItem('lm_token')
  const headers = { Authorization: `Bearer ${token}` }
  const load = async () => { try { const r = await fetch(`${baseurl}${admin ? '/admin/allcomplain' : '/ComplainList'}`, { headers }); if (!r.ok) throw new Error('Could not load reports. Confirm your account has access.'); setItems(getRows(await r.json())) } catch (e) { setState({ loading: false, error: e.message }); return } setState({ loading: false, error: '' }) }
  useEffect(() => { load() }, [])
  const updateStatus = async (item, complete) => { setNotice(''); try { const id = item.complain_id ?? item.id; const r = await fetch(`${baseurl}/admin_status_${complete ? 'complete' : 'progress'}/${id}`, { method: 'PUT', headers }); if (!r.ok) throw new Error('Status update failed.'); setNotice('Report status updated.'); await load() } catch (e) { setNotice(e.message) } }
  const search = async e => { const value = e.target.value; setQuery(value); if (admin && /^\d+$/.test(value)) { try { const r = await fetch(`${baseurl}/admin_search_complain/${value}`, { headers }); if (r.ok) { const data = await r.json(); setItems(getRows(data).length ? getRows(data) : (Array.isArray(data) ? data : [data]).filter(Boolean)) } } catch {} } }
  const visible = items.filter(i => (!query || `${i.title} ${i.description} ${i.location} ${i.complain_id}`.toLowerCase().includes(query.toLowerCase())) && (category === 'All categories' || i.category?.toLowerCase() === category.toLowerCase()))
  const open = items.filter(i => !/complete|resolved/i.test(i.status || '')).length, resolved = items.length - open
  return <main className="page-wrap dashboard"><div className="page-heading"><div><span className="eyebrow">{admin ? 'CITY OPERATIONS' : 'YOUR ACTIVITY'}</span><h1>{admin ? 'Issue management' : 'My reports'}</h1><p>{admin ? 'Review incoming reports and keep residents in the loop.' : 'Track the issues you have reported to the city.'}</p></div>{!admin && <Link className="button button-primary" to="/report">＋ New report</Link>}</div><div className="stat-row"><div className="stat"><span>{admin ? 'All reports' : 'Your reports'}</span><b>{items.length}</b></div><div className="stat"><span>Needs attention</span><b>{open}</b></div><div className="stat"><span>Resolved</span><b>{resolved}</b></div></div><section className="panel management"><div className="management-head"><div><h2>{admin ? 'All city reports' : 'Recent reports'}</h2><p className="muted">{admin ? 'Search by complaint ID and update the status.' : 'Your submissions and their latest status.'}</p></div><div className="filters compact"><label className="search-box">⌕ <input placeholder={admin ? 'Search or enter ID' : 'Search reports'} value={query} onChange={search} /></label><select value={category} onChange={e => setCategory(e.target.value)}><option>All categories</option>{categories.map(c => <option key={c}>{c}</option>)}</select></div></div>{notice && <div className="notice success">{notice}</div>}{state.loading ? <div className="empty-state">Loading reports…</div> : state.error ? <div className="notice error">{state.error}</div> : visible.length === 0 ? <div className="empty-state"><h3>No reports yet</h3><p>When reports are submitted, they will appear here.</p></div> : <div className="table-scroll"><table><thead><tr><th>ISSUE</th><th>LOCATION</th><th>SUBMITTED</th><th>STATUS</th>{admin && <th>ACTIONS</th>}</tr></thead><tbody>{visible.map((item, i) => <tr key={item.complain_id || i}><td><b>{item.title || 'Untitled report'}</b><small>#{item.complain_id ?? item.id ?? '—'} · {item.category}</small></td><td>{item.location || '—'}</td><td>{item.create_at ? new Date(item.create_at).toLocaleDateString() : '—'}</td><td><span className={`issue-status ${statusClass(item.status)}`}>{item.status || 'Pending'}</span></td>{admin && <td><div className="action-group"><button onClick={() => updateStatus(item, false)} disabled={/progress|complete|resolved/i.test(item.status || '')}>Start</button><button onClick={() => updateStatus(item, true)} disabled={/complete|resolved/i.test(item.status || '')}>Resolve</button></div></td>}</tr>)}</tbody></table></div>}</section></main>
}

export default function Home() {
  const [items, setItems] = useState([])
  useEffect(() => { fetch(`${baseurl}/Showallcomplain`).then(r => r.json()).then(data => setItems(getRows(data))).catch(() => {}) }, [])
  return <><section className="hero-section"><div className="hero-copy"><span className="eyebrow"><i /> YOUR VOICE, YOUR COMMUNITY</span><h1>A better neighborhood starts <em>with you.</em></h1><p>Report local issues, follow progress, and help make your community a better place to live.</p><div className="hero-actions"><Link className="button button-primary" to="/report">Report an issue <span>↗</span></Link><Link className="button button-light" to="/explore">Explore reports</Link></div><div className="social-proof"><div className="avatars"><i>J</i><i>M</i><i>A</i><i>+</i></div><div><b>Neighbors making a difference</b><span>One report at a time</span></div></div></div><div className="hero-art"><div className="sun"></div><div className="hill hill-back"></div><div className="hill hill-front"></div><div className="city-label"><span>◉</span><div><b>Small actions.</b><br/>Better streets.</div></div><div className="pin pin-one">✦</div><div className="pin pin-two">✓</div><div className="art-caption">A city that listens<br/><span>starts right here</span></div></div></section><section className="home-feed"><div className="section-heading"><div><span className="eyebrow">WHAT'S HAPPENING</span><h2>Neighbors are speaking up.</h2></div><Link to="/explore">View all reports →</Link></div>{items.length ? <div className="issue-grid">{items.slice(0, 3).map((item, i) => <ReportCard key={item.complain_id || i} item={item} />)}</div> : <div className="feed-empty"><span>✳</span><div><b>Your neighborhood, your voice.</b><p>Be the first to share an issue that needs attention.</p></div><Link className="button button-primary" to="/report">Submit a report →</Link></div>}</section><section id="how-it-works" className="how-section"><span className="eyebrow">HOW CIVICDESK WORKS</span><h2>From report to resolution.</h2><div className="steps"><div><span>01</span><h3>Tell us what’s wrong</h3><p>Share the issue and where it’s happening.</p></div><div><span>02</span><h3>City teams take a look</h3><p>We route your report to the right people.</p></div><div><span>03</span><h3>Track the progress</h3><p>Follow updates until the issue is resolved.</p></div></div></section></>
}
