import { useState } from 'react'
import { Link, useNavigate } from 'react-router'
import { baseurl } from '../API/BaseUrl'

export default function Login() {
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const navigate = useNavigate()
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { const body = new URLSearchParams({ username: email, password }); const r = await fetch(`${baseurl}/User_Login`, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const data = await r.json(); if (!r.ok) throw new Error(data.detail || 'Email or password is incorrect.'); const token = data.access_token; if (!token) throw new Error('Login response did not include an access token.'); localStorage.setItem('lm_token', token); const ur = await fetch(`${baseurl}/user`, { headers: { Authorization: `Bearer ${token}` } }); const user = ur.ok ? await ur.json() : null; localStorage.setItem('civic_user', JSON.stringify(user)); navigate(user?.role?.toLowerCase() === 'admin' ? '/admin' : '/dashboard') } catch (e) { setError(e.message || 'Could not connect to the server.') } finally { setBusy(false) } }
  return <main className="auth-page"><div className="auth-aside"><span className="eyebrow">WELCOME BACK</span><h1>Good to see you.</h1><p>Sign in to keep your community moving forward.</p><div className="aside-note">“The best way to find yourself is to lose yourself in the service of others.”<small>— Mahatma Gandhi</small></div></div><form className="panel auth-card" onSubmit={submit}><span className="eyebrow">YOUR CIVICDESK ACCOUNT</span><h2>Log in</h2><p className="muted">Enter your details to continue.</p>{error && <div className="notice error">{error}</div>}<label>Email address<input type="email" required autoComplete="email" placeholder="you@example.com" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" required autoComplete="current-password" placeholder="Enter your password" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="button button-primary full" disabled={busy}>{busy ? 'Signing in…' : 'Sign in →'}</button><p className="auth-foot">New to CivicDesk? <Link to="/registration">Create an account</Link></p></form></main>
}
