import { useState } from 'react'
import { Link, useNavigate } from 'react-router'
import { baseurl } from '../API/BaseUrl'

export default function Register() {
  const [form, setForm] = useState({ name: '', email: '', password: '' }), [error, setError] = useState(''), [busy, setBusy] = useState(false), navigate = useNavigate()
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { const r = await fetch(`${baseurl}/create_user`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, role: 'user' }) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.detail || 'Could not create your account.'); navigate('/login', { state: { registered: true } }) } catch (e) { setError(e.message || 'Could not connect to the server.') } finally { setBusy(false) } }
  return <main className="auth-page"><div className="auth-aside"><span className="eyebrow">JOIN YOUR COMMUNITY</span><h1>Let’s make our city better.</h1><p>One report can make a real difference on your block.</p><div className="aside-note">“Never doubt that a small group of thoughtful citizens can change the world.”<small>— Margaret Mead</small></div></div><form className="panel auth-card" onSubmit={submit}><span className="eyebrow">GET STARTED</span><h2>Create your account</h2><p className="muted">It only takes a moment to join in.</p>{error && <div className="notice error">{error}</div>}<label>Full name<input required minLength="3" maxLength="30" autoComplete="name" placeholder="Your name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Email address<input required type="email" autoComplete="email" placeholder="you@example.com" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Password<input required type="password" minLength="8" maxLength="30" autoComplete="new-password" placeholder="At least 8 characters" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label><button className="button button-primary full" disabled={busy}>{busy ? 'Creating account…' : 'Create account →'}</button><p className="auth-foot">Already have an account? <Link to="/login">Sign in</Link></p></form></main>
}
